### PR TITLE
Dockerized version of the STViewer

### PR DESCRIPTION
**Pull request by mattions**
This is a first Attempt to dockering the ST_viewer, connected with #24 

@jfnavarro I couldn't manage to make to have a succesful `cmake` run.
It seems R fails to find `lapack`, but it's currently installed.

Do you have any suggestion how to fix it?

These is what I get:

```
root@3c1aa55f5a22:/opt/st_viewer/st_viewer_build# cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_PREFIX_PATH="/opt/QCustomPlot/qcustomplot" ..
-- The CXX compiler identification is GNU 7.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- 
-- -------------------------------------------------------------------------------
-- Building Spatial Transcriptomics Research Viewer .....
-- Change a configuration variable with: cmake -D<Variable>=<Value>
-- CMAKE_INSTALL_PREFIX = /usr/local
-- CMAKE_BUILD_TYPE = Release
-- CMAKE_PREFIX_PATH = /opt/QCustomPlot/qcustomplot
-- CMAKE_CXX_COMPILER = /usr/bin/c++
-- TARGET_ARCH = 
-- VERSION = 0.7.0
-- CONFIGURATION FILE = /opt/st_viewer/assets/stviewer.conf
-- -------------------------------------------------------------------------------
-- 
-- Building a release version...
-- Performing Test COMPILER_SUPPORTS_PIC
-- Performing Test COMPILER_SUPPORTS_PIC - Success
-- Found Armadillo: /usr/lib/libarmadillo.so (found version "7.960.1") 
-- Found R include dir: /usr/share/R/include
-- Found R libraries: /usr/lib/R/lib/libR.so
-- Found R blas libraries: /usr/lib/x86_64-linux-gnu/libblas.so
CMake Warning (dev) in cmake/FindR.cmake:
  A logical block opening on the line

    /opt/st_viewer/cmake/FindR.cmake:157 (if)

  closes on the line

    /opt/st_viewer/cmake/FindR.cmake:159 (endif)

  with mis-matching arguments.
Call Stack (most recent call first):
  src/CMakeLists.txt:54 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Rcpp: /usr/local/lib/R/site-library/Rcpp/include
-- Found RInside: /usr/local/lib/R/site-library/RInside/include
-- Found RInside libraries: -L/usr/local/lib/R/site-library/RInside/lib -lRInside -Wl,-rpath,/usr/local/lib/R/site-library/RInside/lib
-- Found RcppArmadillo: /usr/local/lib/R/site-library/RcppArmadillo/include
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBR_LAPACK_LIBRARY
    linked by target "STViewer" in directory /opt/st_viewer/src
    linked by target "tst_mathextendedtest" in directory /opt/st_viewer/src/test
    linked by target "tst_widgets" in directory /opt/st_viewer/src/test
    linked by target "tst_glheatmaptest" in directory /opt/st_viewer/src/test

-- Configuring incomplete, errors occurred!
See also "/opt/st_viewer/st_viewer_build/CMakeFiles/CMakeOutput.log".
```

### CODE REVIEW

**Comment by jfnavarro** [comment]
Hi! This is great! 
I have made some adjustments in the FindR.cmake code. Could you try again?

**Comment by mattions** [comment]
@jfnavarro I managed to pass the Cmake now.

However I have a problem during the compilation step.

This is the log:

```
Step 17/18 : RUN make -j4
 ---> Running in af96d6bf6dfc
Scanning dependencies of target qcustomplot_automoc
Scanning dependencies of target color_automoc
Scanning dependencies of target STViewer_automoc
Scanning dependencies of target dialogs_automoc
[  2%] Automatic moc, uic and rcc for target STViewer
[  1%] Automatic moc, uic and rcc for target dialogs
[  4%] Automatic moc, uic and rcc for target qcustomplot
[  4%] Automatic moc, uic and rcc for target color
Generating moc compilation color_automoc.cpp
[  4%] Built target color_automoc
Scanning dependencies of target data_automoc
[  6%] Automatic moc, uic and rcc for target data
Generating moc source data_automoc.dir/moc_DatasetImporte_4M5M5SNPN5AQK3.cpp
Generating moc compilation data_automoc.cpp
Generating ui header ui_datasetImporter.h
Generating moc source STViewer_automoc.dir/moc_mainWindow_6SGJLJGLZKNQQK.cpp
Generating moc compilation STViewer_automoc.cpp
Generating qrc source STViewer_automoc.dir/qrc_application_ZMTBKQCDPOJKOF.cpp
[  6%] Built target data_automoc
Scanning dependencies of target viewTables_automoc
[  6%] Built target STViewer_automoc
[  7%] Automatic moc, uic and rcc for target viewTables
Scanning dependencies of target viewPages_automoc
[  8%] Automatic moc, uic and rcc for target viewPages
Generating moc source qcustomplot_automoc.dir/moc_qcustomplot_UTAO5OGUB3MJIH.cpp
Generating moc compilation qcustomplot_automoc.cpp
[  8%] Built target qcustomplot_automoc
Generating moc source dialogs_automoc.dir/moc_AboutDialog_BYN65AE67ADZXV.cpp
Generating moc source dialogs_automoc.dir/moc_EditDatasetDia_UJLPCS3X7HEUL4.cpp
Generating moc source dialogs_automoc.dir/moc_EditSelectionD_342DPTRDNJQFMI.cpp
Generating moc source dialogs_automoc.dir/moc_SelectionDialo_T3YGLWGZAIOODH.cpp
Generating moc compilation dialogs_automoc.cpp
Generating ui header ui_aboutdialog.h
Generating ui header ui_editDatasetDialog.h
Generating ui header ui_editSelectionDialog.h
Generating ui header ui_selectionConsole.h
Scanning dependencies of target viewRenderer_automoc
[  8%] Built target dialogs_automoc
[  9%] Automatic moc, uic and rcc for target viewRenderer
Scanning dependencies of target model_automoc
[ 10%] Automatic moc, uic and rcc for target model
Generating moc source viewTables_automoc.dir/moc_DatasetsTableV_7AOBWEQ7KIYP7L.cpp
Generating moc source viewTables_automoc.dir/moc_GenesTableView_TZGDAOPLQVWR3B.cpp
Generating moc source viewTables_automoc.dir/moc_SpotsTableView_5VX4PRELXR73VM.cpp
Generating moc source viewTables_automoc.dir/moc_UserSelectionT_LWNYTMXNY7MC33.cpp
Generating moc compilation viewTables_automoc.cpp
[ 10%] Built target viewTables_automoc
Scanning dependencies of target config_automoc
[ 12%] Automatic moc, uic and rcc for target config
Generating moc compilation config_automoc.cpp
[ 12%] Built target config_automoc
Scanning dependencies of target math_automoc
[ 13%] Automatic moc, uic and rcc for target math
Generating moc compilation math_automoc.cpp
[ 13%] Built target math_automoc
Scanning dependencies of target analysis_automoc
[ 14%] Automatic moc, uic and rcc for target analysis
Generating moc source model_automoc.dir/moc_DatasetItemMod_NXA6NBLWBD4624.cpp
Generating moc source model_automoc.dir/moc_GeneItemModel_CCJOIKQZDQENUY.cpp
Generating moc source model_automoc.dir/moc_SpotItemModel_U2PF5UQZVDLIL3.cpp
Generating moc source model_automoc.dir/moc_UserSelections_YS5PKXZAPSSOVS.cpp
Generating moc compilation model_automoc.cpp
[ 14%] Built target model_automoc
Scanning dependencies of target tst_mathextendedtest_automoc
[ 15%] Automatic moc, uic and rcc for target tst_mathextendedtest
Generating moc source tst_mathextendedtest.moc
/opt/st_viewer/src/test/utils/tst_mathextendedtest.cpp:0: Note: No relevant classes found. No output generated.
Generating moc source tst_mathextendedtest_automoc.dir/moc_tst_mathextend_UL4UXOZVOYMNMZ.cpp
Generating moc compilation tst_mathextendedtest_automoc.cpp
[ 15%] Built target tst_mathextendedtest_automoc
Generating moc source viewRenderer_automoc.dir/moc_CellGLView_QER74UTOJOG5DV.cpp
Generating moc source viewRenderer_automoc.dir/moc_GeneRendererGL_VQH7ENPZ44SNLZ.cpp
Generating moc source viewRenderer_automoc.dir/moc_GraphicItemGL_RJBMPJYOI4MTBF.cpp
Generating moc source viewRenderer_automoc.dir/moc_HeatMapLegendG_SPTAWGTFO2FQ64.cpp
Generating moc source viewRenderer_automoc.dir/moc_ImageTextureGL_K54UL2EQEEL5AO.cpp
Generating moc compilation viewRenderer_automoc.cpp
[ 15%] Built target viewRenderer_automoc
Scanning dependencies of target tst_widgets_automoc
Scanning dependencies of target tst_glheatmaptest_automoc
[ 16%] Automatic moc, uic and rcc for target tst_widgets
[ 18%] Automatic moc, uic and rcc for target tst_glheatmaptest
Generating moc source tst_widgets.moc
/opt/st_viewer/src/test/controller/tst_widgets.cpp:0: Note: No relevant classes found. No output generated.
Generating moc source tst_widgets_automoc.dir/moc_tst_widgets_GRKI5FCJDNDHGY.cpp
Generating moc compilation tst_widgets_automoc.cpp
[ 18%] Built target tst_widgets_automoc
Generating moc source tst_glheatmaptest.moc
/opt/st_viewer/src/test/math/tst_glheatmaptest.cpp:0: Note: No relevant classes found. No output generated.
Generating moc source viewPages_automoc.dir/moc_CellViewPage_277LFKHWLX4ZPS.cpp
Generating moc source viewPages_automoc.dir/moc_DatasetPage_DYVZ5SKYNTH6PA.cpp
Generating moc source viewPages_automoc.dir/moc_GenesWidget_QKCIRAMHIIJPVQ.cpp
Generating moc source viewPages_automoc.dir/moc_SelectionGenes_GBUMWYRG5AEUQC.cpp
Generating moc source viewPages_automoc.dir/moc_SelectionSpots_VJR3UABNRPKN5G.cpp
Generating moc source viewPages_automoc.dir/moc_SettingsWidget_SBS4KCHFRUVXXI.cpp
Generating moc source viewPages_automoc.dir/moc_SpotsWidget_BJKLN5ZR3OETSO.cpp
Generating moc source viewPages_automoc.dir/moc_UserSelections_A4V7NB7AZGY3HJ.cpp
Generating moc compilation viewPages_automoc.cpp
Generating ui header ui_cellviewPage.h
Generating ui header ui_datasetsPage.h
Generating ui header ui_genesSelectionWidget.h
Generating ui header ui_spotsSelectionWidget.h
Generating ui header ui_SettingsWidget.h
Generating ui header ui_selectionsPage.h
[ 18%] Built target viewPages_automoc
Generating moc source tst_glheatmaptest_automoc.dir/moc_tst_glheatmapt_MBAL7SXHJ766JW.cpp
Generating moc compilation tst_glheatmaptest_automoc.cpp
Scanning dependencies of target qcustomplot
[ 18%] Built target tst_glheatmaptest_automoc
[ 19%] Building CXX object src/CMakeFiles/qcustomplot.dir/opt/QCustomPlot/qcustomplot/qcustomplot.cpp.o
Scanning dependencies of target dialogs
[ 20%] Building CXX object src/dialogs/CMakeFiles/dialogs.dir/AboutDialog.cpp.o
Scanning dependencies of target color
[ 21%] Building CXX object src/color/CMakeFiles/color.dir/HeatMap.cpp.o
Generating moc source analysis_automoc.dir/moc_AnalysisCluste_77OFC63AZESZUR.cpp
Generating moc source analysis_automoc.dir/moc_AnalysisCorrel_ZSKC5O3YZNCV2Q.cpp
Generating moc source analysis_automoc.dir/moc_AnalysisDEA_X6S75DANXJVHMP.cpp
Generating moc source analysis_automoc.dir/moc_AnalysisPCA_HI5DJAPYA7ANNV.cpp
Generating moc source analysis_automoc.dir/moc_AnalysisQC_2JDG3VHHWDVVGW.cpp
Generating moc source analysis_automoc.dir/moc_AnalysisScatte_4ZYQH666A3S2OQ.cpp
Generating moc source analysis_automoc.dir/moc_ChartView_YLXZ7KHMWM4EAN.cpp
Generating moc compilation analysis_automoc.cpp
Generating ui header ui_analysisClustering.h
Generating ui header ui_analysisCorrelation.h
Generating ui header ui_analysisDEA.h
Generating ui header ui_AnalysisPCA.h
Generating ui header ui_analysisQC.h
Generating ui header ui_analysisScatter.h
[ 21%] Built target analysis_automoc
[ 22%] Building CXX object src/dialogs/CMakeFiles/dialogs.dir/SelectionDialog.cpp.o
Scanning dependencies of target data
[ 24%] Building CXX object src/data/CMakeFiles/data.dir/DatasetImporter.cpp.o
[ 25%] Building CXX object src/dialogs/CMakeFiles/dialogs.dir/EditSelectionDialog.cpp.o
[ 26%] Building CXX object src/color/CMakeFiles/color.dir/color_automoc.cpp.o
[ 26%] Built target color
Scanning dependencies of target viewTables
[ 27%] Building CXX object src/viewTables/CMakeFiles/viewTables.dir/DatasetsTableView.cpp.o
[ 28%] Building CXX object src/data/CMakeFiles/data.dir/Dataset.cpp.o
[ 30%] Building CXX object src/dialogs/CMakeFiles/dialogs.dir/EditDatasetDialog.cpp.o
[ 31%] Building CXX object src/viewTables/CMakeFiles/viewTables.dir/GenesTableView.cpp.o
[ 32%] Building CXX object src/dialogs/CMakeFiles/dialogs.dir/dialogs_automoc.cpp.o
[ 32%] Built target dialogs
Scanning dependencies of target viewPages
[ 33%] Building CXX object src/viewPages/CMakeFiles/viewPages.dir/CellViewPage.cpp.o
[ 34%] Building CXX object src/data/CMakeFiles/data.dir/Spot.cpp.o
[ 36%] Building CXX object src/data/CMakeFiles/data.dir/Gene.cpp.o
[ 37%] Building CXX object src/viewTables/CMakeFiles/viewTables.dir/SpotsTableView.cpp.o
[ 38%] Building CXX object src/data/CMakeFiles/data.dir/UserSelection.cpp.o
[ 39%] Building CXX object src/viewTables/CMakeFiles/viewTables.dir/UserSelectionTableView.cpp.o
In file included from /usr/local/lib/R/site-library/RcppArmadillo/include/armadillo:562:0,
                 from /opt/st_viewer/src/data/STData.h:16,
                 from /opt/st_viewer/src/data/UserSelection.h:5,
                 from /opt/st_viewer/src/data/UserSelection.cpp:1:
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp: In static member function 'static void arma::arrayops::copy_small(eT*, const eT*, arma::uword) [with eT = double]':
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:48:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  9:  dest[ 8] = src[ 8];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:49:5: note: here
     case  8:  dest[ 7] = src[ 7];
     ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:49:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  8:  dest[ 7] = src[ 7];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:50:5: note: here
     case  7:  dest[ 6] = src[ 6];
     ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:50:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  7:  dest[ 6] = src[ 6];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:51:5: note: here
     case  6:  dest[ 5] = src[ 5];
     ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:51:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  6:  dest[ 5] = src[ 5];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:52:5: note: here
     case  5:  dest[ 4] = src[ 4];
     ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:52:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  5:  dest[ 4] = src[ 4];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:53:5: note: here
     case  4:  dest[ 3] = src[ 3];
     ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:53:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  4:  dest[ 3] = src[ 3];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:54:5: note: here
     case  3:  dest[ 2] = src[ 2];
     ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:54:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  3:  dest[ 2] = src[ 2];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:55:5: note: here
     case  2:  dest[ 1] = src[ 1];
     ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:55:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  2:  dest[ 1] = src[ 1];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:56:5: note: here
     case  1:  dest[ 0] = src[ 0];
     ^~~~
cc1plus: all warnings being treated as errors
src/data/CMakeFiles/data.dir/build.make:158: recipe for target 'src/data/CMakeFiles/data.dir/UserSelection.cpp.o' failed
make[2]: *** [src/data/CMakeFiles/data.dir/UserSelection.cpp.o] Error 1
CMakeFiles/Makefile2:465: recipe for target 'src/data/CMakeFiles/data.dir/all' failed
make[1]: *** [src/data/CMakeFiles/data.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 40%] Building CXX object src/viewPages/CMakeFiles/viewPages.dir/DatasetPage.cpp.o
[ 42%] Building CXX object src/viewTables/CMakeFiles/viewTables.dir/viewTables_automoc.cpp.o
[ 43%] Building CXX object src/viewPages/CMakeFiles/viewPages.dir/UserSelectionsPage.cpp.o
[ 43%] Built target viewTables
[ 44%] Building CXX object src/CMakeFiles/qcustomplot.dir/qcustomplot_automoc.cpp.o
[ 45%] Building CXX object src/viewPages/CMakeFiles/viewPages.dir/GenesWidget.cpp.o
[ 46%] Building CXX object src/viewPages/CMakeFiles/viewPages.dir/SpotsWidget.cpp.o
In file included from /usr/local/lib/R/site-library/RcppArmadillo/include/armadillo:562:0,
                 from /opt/st_viewer/src/data/STData.h:16,
                 from /opt/st_viewer/src/data/UserSelection.h:5,
                 from /opt/st_viewer/src/viewPages/SelectionGenesWidget.h:7,
                 from /opt/st_viewer/src/viewPages/UserSelectionsPage.cpp:9:
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp: In static member function 'static void arma::arrayops::copy_small(eT*, const eT*, arma::uword) [with eT = double]':
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:48:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  9:  dest[ 8] = src[ 8];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:49:5: note: here
     case  8:  dest[ 7] = src[ 7];
     ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:49:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  8:  dest[ 7] = src[ 7];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:50:5: note: here
     case  7:  dest[ 6] = src[ 6];
     ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:50:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  7:  dest[ 6] = src[ 6];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:51:5: note: here
     case  6:  dest[ 5] = src[ 5];
     ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:51:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  6:  dest[ 5] = src[ 5];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:52:5: note: here
     case  5:  dest[ 4] = src[ 4];
     ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:52:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  5:  dest[ 4] = src[ 4];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:53:5: note: here
     case  4:  dest[ 3] = src[ 3];
     ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:53:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  4:  dest[ 3] = src[ 3];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:54:5: note: here
     case  3:  dest[ 2] = src[ 2];
     ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:54:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  3:  dest[ 2] = src[ 2];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:55:5: note: here
     case  2:  dest[ 1] = src[ 1];
     ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:55:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  2:  dest[ 1] = src[ 1];
               ^~~~
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/arrayops_meat.hpp:56:5: note: here
     case  1:  dest[ 0] = src[ 0];
     ^~~~
[ 48%] Building CXX object src/viewPages/CMakeFiles/viewPages.dir/SelectionGenesWidget.cpp.o
[ 49%] Building CXX object src/viewPages/CMakeFiles/viewPages.dir/SelectionSpotsWidget.cpp.o
[ 50%] Linking CXX shared library ../libqcustomplot.so
[ 50%] Built target qcustomplot
[ 51%] Building CXX object src/viewPages/CMakeFiles/viewPages.dir/SettingsWidget.cpp.o
cc1plus: all warnings being treated as errors
src/viewPages/CMakeFiles/viewPages.dir/build.make:110: recipe for target 'src/viewPages/CMakeFiles/viewPages.dir/UserSelectionsPage.cpp.o' failed
make[2]: *** [src/viewPages/CMakeFiles/viewPages.dir/UserSelectionsPage.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/viewPages/CMakeFiles/viewPages.dir/all] Error 2
CMakeFiles/Makefile2:641: recipe for target 'src/viewPages/CMakeFiles/viewPages.dir/all' failed
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c make -j4' returned a non-zero code: 2
```

**Comment by jfnavarro** [comment]
A warning being thrown from the Armadillo code. The ST Viewer treats warnings as errors except few exceptions. That warning could be added to the exceptions list but I wonder what version of Armadillo and Qt are you installing using APT? Probably newer versions do not throw that warning.

**Comment by jfnavarro** [comment]
I meant RcppArmadillo

**Comment by mattions** [comment]
How can I check?

I think the `RcppArmadillo` I'm installing is the one that R is pulling from CRAN?

This is the line: https://github.com/jfnavarro/st_viewer/pull/25/files#diff-3254677a7917c6c01f55212f86c57fbfR70

and that is what is suggested in the Readme.

Happy to go for later version if it helps, just let me know which one should I aim for

**Comment by mattions** [comment]
Qt version 5.9.1, and Armadillo version 1:7.960.1
Full APT search below

```
oot@8bb46660967b:/opt/st_viewer/st_viewer_build# apt search qt5-default
Sorting... Done
Full Text Search... Done
qt5-default/artful,now 5.9.1+dfsg-10ubuntu1 amd64 [installed]
  Qt 5 development defaults package

root@8bb46660967b:/opt/st_viewer/st_viewer_build# apt search libarmadillo-dev
Sorting... Done
Full Text Search... Done
libarmadillo-dev/artful,now 1:7.960.1+dfsg-1 amd64 [installed]
  streamlined C++ linear algebra library - Headers
```

**Comment by jfnavarro** [comment]
I disabled that warning, could you try now?

**Comment by jfnavarro** [comment]
Does this work now? Is it good performance wise? I mean if the GUI is responsive and fast being run from a container.

**Comment by mattions** [comment]
hi @jfnavarro I've managed to compile it.

Now I need to figure out how to launch the GUI and then how to mount the directories :).

I've figured out the first, now I'm onto the second.

I'm getting there though, and the STViewer looks pretty sprite when run from the container (no datasts yet loaded)

**Comment by mattions** [comment]
@jfnavarro the cointainer loads the datasets and works pretty well on my system AFAIK.

I have also a file to install all the dependencies, compile and link the STViewer on an ubuntu machine. 
I was wondering if I can add that also to the repo and to the README in this one, or in a dedicated branch.

Let me know what you think.

**Pull request merged**
